-- Conversation History synced across devices via Cloudflare D1.
--
-- Timestamps are ISO-8601 strings generated by the Worker; message ordering is
-- (created_at, rowid) so messages written in the same millisecond keep insertion
-- order. Deleting a session removes its messages explicitly inside a D1 batch
-- transaction (see lib/conversation-db.ts); the FK cascade is declared for
-- defense-in-depth but is not required to be enabled on every connection.

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  parts TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_session_created
  ON messages(session_id, created_at);

CREATE INDEX IF NOT EXISTS idx_sessions_updated
  ON sessions(updated_at);
